base_agv_node:
  ros__parameters:
    emergency_stop_enabled: true
    min_safety_distance: 0.3
    max_speed: 2.0
    max_acceleration: 1.0
    update_rate: 20.0
    log_level: "INFO"
    
    plc_timeout: 5.0


