
AGV03:
  agv_core_node:
    ros__parameters:
      device_id: "FORK02"
      device_type: "FORK"
      description: "EBD牙叉型AGV #2"
      max_speed: 1.5
      max_payload: 500
      safety_distance: 0.5

  plc_service:
    ros__parameters:
      plc_ip: "192.168.2.100"
      plc_port: 8501
