
{
      "forward": "3600",
      "backward": "3601",
      "rotate_left": "3602",
      "rotate_right": "3603",
      "shift_left": "3604",
      "shift_right": "3605",
      "break": "3606",
      "enable": "3607",
      "auto1": "4001",
      "auto2": "0",
      "stop": "3701",
      "reset": "302",
      "send_mission_from": "2990",
      "send_mission_to": "2991",
      "send_mission_magic": "2993",
      "cancel_mission": "7001",
      "traffic_stop": "7002",
      }
           