hokuyo_dms_cargo02_1:
  device: "MR"
  address: "5800"

hokuyo_dms_cargo02_2:
  device: "MR"
  address: "6000"

hokuyo_dms_unloader02:
  device: "MR"
  address: "100"
  
hokuyo_dms_loader02:
  device: "MR"
  address: "100"
 