agv01:
  plc_service:
    ros__parameters:
      plc_ip: "192.168.2.100"
      read_ranges:
        - "DM,7600,200"

agv02:
  plc_service:
    ros__parameters:
      plc_ip: "192.168.2.100"
      read_ranges:
        - "DM,7600,200"
cargo02:
  plc_service:
    ros__parameters:
      plc_ip: "192.168.2.100"
      read_ranges:
        - "DM,7600,200"

loader02:
  plc_service:
    ros__parameters:
      plc_ip: "192.168.2.100"
      read_ranges:
        - "DM,7600,200"
        
unloader02:
  plc_service:
    ros__parameters:
      plc_ip: "192.168.2.100"
      read_ranges:
        - "DM,7600,200"

agvc:
  plc_service:
    ros__parameters:
      plc_ip: "192.168.2.100"
      read_ranges:
        - "DM,7600,20"
        - "DM,11000,20"

  ecs_core:
    ros__parameters:
      read_ranges:
        - "DM,7600,200"
        - "DM,11000,20"

  door_controller_node_mqtt:
    ros__parameters:
      broker_host: "192.168.11.206"
      broker_port: 2883
      username: "DsH8vSx2uhTao1hlc9vx"
      sub_topic: "request/to/agvc/door"
      pub_topic: "response/to/kukaecs/door"
      doors:
        - "1,MR,100,DM,5000"
        - "2,MR,101,DM,5001"
        - "3,MR,102,DM,5002"
        - "4,MR,103,DM,5003"
        - "5,MR,104,DM,5004"

