name: test_flow_designer_dsl
description: Flow Designer 創建的流程 - test_flow_designer_dsl
priority: 50
work_id: ''
enabled: true
trigger_conditions: []
action:
  type: create_task
  task_type: custom
applicable_locations: []
debug:
  enabled: false
  log_conditions: true
  dry_run: false
flow_designer_data:
  version: '1.0'
  nodes:
  - id: create_task_from_decision_1
    type: create_task_from_decision
    name: 從決策創建任務
    description: ''
    position:
      x: 449
      y: 250
    parameters: {}
  - id: check_agv_rotation_flow_2
    type: check_agv_rotation_flow
    name: AGV 旋轉流程檢查
    description: ''
    position:
      x: 139
      y: 124
    parameters: {}
  connections:
  - id: 186e1add953b0458
    source: check_agv_rotation_flow_2
    sourceOutput: decisions
    target: create_task_from_decision_1
    targetInput: decision
  created: '2025-08-05T14:06:31.609Z'
  updated: '2025-08-05T14:06:31.621520'
