metadata:
  id: test_nested_cleaning_v2
  name: Test Nested Card ID Cleaning V2
  version: '1.1'
  updated_at: '2025-08-28T06:53:17.193892'
  created_at: '2025-08-28T06:53:17.193899'
settings: {}
preload: {}
rules: {}
variables:
  agv_id: agv01
  task_priority: 5
flow:
- notify:
    level: info
    message: Start
- if:
    condition: ${task_priority} > 5
    then:
    - create:
        target: task
        with:
          id: task_001
          priority: high
    else:
    - notify:
        level: debug
        message: Normal priority
- switch:
    expression: ${task_priority}
    cases:
    - when: '> 8'
      do:
      - query:
          target: task
          where:
            id: task_urgent
          limit: 10
    default:
    - notify:
        level: warning
        message: Default case
